version: '3.8'

services:
  fiber-app:
    image: fiber-app
    container_name: fiber-app
    env_file:
      - .env
    ports:
      - 8080:8080
    networks:
      - admin-networks
    volumes:
      - product-image:/app/uploads
    depends_on:
      admin-data:
        condition: service_healthy
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G

  admin-data:
    image: mysql:latest
    restart: always
    container_name: admin-data
    environment:
      MYSQL_DATABASE: catering
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - admin-data:/var/lib/mysql
    networks:
      - admin-networks
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_PASS}"]
      interval: 10s
      timeout: 5s
      retries: 5

  migrate:
    image: migrate/migrate
    container_name: migrate
    env_file:
      - .env
    volumes:
      - /home/andhikadanger/Documents/khaira-catering-online/khaira-admin/db/migrations:/migrations
    command: [
      "-path", "/migrations",
      "-database", "mysql://root:${DB_PASS}@tcp(admin-data:${DB_PORT})/${DB_NAME}",
      "up"
    ]
    depends_on:
      admin-data:
        condition: service_healthy
    networks:
      - admin-networks

networks:
  admin-networks:

volumes:
  admin-data:
  product-image: