version: '3.8'

services:
  fiber-app:
    image: ghcr.io/anotherdanger/khaira-admin:1.3
    container_name: fiber-app
    env_file:
      - .env
    ports:
      - 8082:8082
    networks:
      - admin-networks
    volumes:
      - product-image:/app/uploads
    depends_on:
      admin-data:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G

  admin-data:
    image: mysql:latest
    restart: always
    container_name: admin-data
    environment:
      MYSQL_DATABASE: catering
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - admin-data:/var/lib/mysql
    networks:
      - admin-networks
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_PASS}"]
      interval: 10s
      timeout: 5s
      retries: 5

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - admin-networks
    healthcheck:
      test: curl --silent --fail http://localhost:9200/_cluster/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 5

  jwt-auth:
    container_name: jwt-auth
    image: ghcr.io/anotherdanger/khaira-jwt-auth:latest
    env_file:
      - .env
    ports:
     - 8081:8081
    networks:
      - admin-networks

  

networks:
  admin-networks:

volumes:
  admin-data:
  product-image:
  esdata:
