// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gofiber/fiber/v2"
	"github.com/google/wire"
	"khaira-admin/controller"
	"khaira-admin/helper"
	"khaira-admin/repository"
	"khaira-admin/service"
)

// Injectors from injector.go:

func InitServer() (*fiber.App, func(), error) {
	repositoryRepository := repository.NewRepositoryImpl()
	db, cleanup, err := helper.NewDb()
	if err != nil {
		return nil, nil, err
	}
	serviceService := service.NewServiceImpl(repositoryRepository, db)
	controllerController := controller.NewControllerImpl(serviceService)
	app := NewServer(controllerController)
	return app, func() {
		cleanup()
	}, nil
}

// injector.go:

var ServerSet = wire.NewSet(repository.NewRepositoryImpl, service.NewServiceImpl, controller.NewControllerImpl, helper.NewDb, NewServer)
